spring.application.name=backend
server.port=9090
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
hibernate.transaction.jta.platform=org.hibernate.service.jta.platform.internal.JBossAppServerJtaPlatform
spring.cache.type=simple
admin.username=admin
admin.password=password123#
jwt.secret=XvMI5WPN/OjxtOuSeUSWd4RlkCdM5EUYWPd4FPaKNOs=
